---
title: "Probing results"
output: html_document #with html_notebook you get a printout of the notebook
---

# SETUP

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) 
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(grid)
library(gridExtra)
library(operator.tools)
library(lme4)
library(lmerTest)
library(cocor)
library(patchwork)
library(gtools)
library(cowplot)
library(RColorBrewer)
library(svglite)


source('dataloader_utils.R') #includes normalizations, read_data functions
source('stats_utils.R')

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

## Output dir
```{r}
path <- paste("results/")
ifelse(!dir.exists(path), dir.create(path), FALSE)
savedir <- paste(path,"Probing",sep='')
ifelse(!dir.exists(savedir), dir.create(savedir), FALSE)
```


# READ DATA
```{r}
model2plausibility_dir = "../probing/results/model2plausibility"

read_data <- function(directory, filename) {
    metadata = str_split(filename, "_")[[1]]
    d = read.delim(paste(directory, filename, sep='/'), 
                   header=FALSE, sep=',')
    # stacking data from iterations
    d = data.frame(d[1], stack(d[2:ncol(d)]))
    d = d %>%
      mutate(Model = metadata[[1]]) %>%
      mutate(Model = ifelse(grepl("roberta", Model), "RoBERTa", Model)) %>%
      mutate(Model = ifelse(grepl("bert", Model), "BERT", Model)) %>%
      mutate(Model = ifelse(grepl("gpt2", Model), "GPT-2", Model)) %>%
      mutate(Model = ifelse(grepl("gpt-j", Model), "GPT-J", Model))  %>%
      mutate(Dataset = metadata[[2]]) %>%
      mutate(VoiceType = metadata[[3]]) %>%
      mutate(VoiceType = ifelse(grepl("EventsAdapt",Dataset),
                                ifelse(length(str_split(VoiceType, "-")[[1]]) > 1,
                                      paste0("TrainOn:",str_split(VoiceType, "-")[[1]][1],"-TestOn:",str_split(VoiceType, "-")[[1]][2]),
                                VoiceType),
                          VoiceType)) %>%
      mutate(VoiceType = ifelse(VoiceType == "normal", "all", VoiceType)) %>%
      mutate(TrialType = metadata[[4]]) %>%
      mutate(TrialType = str_replace(TrialType, ".csv", "")) %>%
      mutate(TrialType = ifelse(grepl("EventsAdapt",Dataset),
                                ifelse(length(str_split(TrialType, "-")[[1]]) > 1,
                                       paste0("TrainOn:",str_split(TrialType, "-")[[1]][1],"-TestOn:",str_split(TrialType, "-")[[1]][2]),
                                TrialType),
                          TrialType)) %>%
      mutate(TrialType = ifelse(TrialType == "normal", "all", TrialType)) %>%
      dplyr::rename(Layer = V1) %>%
      dplyr::rename(Accuracy = values)  %>%
      dplyr::rename(Iteration = ind)  %>%
      mutate(Iteration = str_replace(as.character(Iteration), "V", "")) %>%
      mutate(Iteration = as.numeric(Iteration)-2) %>%
      mutate(Plot = paste(Model, Dataset, VoiceType, TrialType, sep = " ")) %>%
      mutate(Plot = str_replace(Plot, "all all", ""))

    #reorder columns
    d <- d[, c("Dataset", "Model", "VoiceType", "TrialType", "Layer", "Iteration", "Accuracy", "Plot")]
}

```


```{r}
filenames = list.files(path=model2plausibility_dir, pattern='*.csv')
dat.models = do.call(rbind, lapply(filenames, function(x) read_data(model2plausibility_dir, x)))

dat = dat.models

dat$Layer = as.factor(dat$Layer)
dat$Model = factor(dat$Model, levels=c("RoBERTa","BERT", "GPT-J", "GPT-2"))
```

# READ HUMAN CEILING DATA
```{r}
model2human_dir = "../probing/results/model2human_ceiling"

read_data <- function(directory, filename) {
  metadata = str_split(filename, "_")[[1]]
  d = read.delim(paste(model2human_dir, filename, sep='/'), 
                 header=FALSE, sep=',')
  d = d %>%
    mutate(Dataset = metadata[[2]]) %>%
    mutate(VoiceType = metadata[[3]]) %>%
    mutate(VoiceType = ifelse(grepl("EventsAdapt",Dataset),
                          ifelse(length(str_split(VoiceType, "-")[[1]]) > 1,
                                paste0("TrainOn:",str_split(VoiceType, "-")[[1]][1],"-TestOn:",str_split(VoiceType, "-")[[1]][2]),
                          VoiceType),
                    VoiceType)) %>%
    mutate(VoiceType = ifelse(VoiceType == "normal", "all", VoiceType)) %>%
    mutate(TrialType = metadata[[4]]) %>%
    mutate(TrialType = str_replace(TrialType, ".csv", "")) %>%
    mutate(TrialType = ifelse(grepl("EventsAdapt",Dataset), 
                                ifelse(length(str_split(TrialType, "-")[[1]]) > 1,
                                       paste0("TrainOn:",str_split(TrialType, "-")[[1]][1],"-TestOn:",str_split(TrialType, "-")[[1]][2]),
                                TrialType),
                        TrialType)) %>%
    mutate(TrialType = ifelse(TrialType == "normal", "all", TrialType)) %>%
    dplyr::rename(Iteration = V1)  %>%
    dplyr::rename(Accuracy = V2)  %>%
    mutate(Model = "HumanCeiling") %>%
    mutate(Plot = paste(Model, Dataset, VoiceType, TrialType, sep = " ")) %>%
    mutate(Plot = str_replace(Plot, "all all", ""))
}

filenames = list.files(path=model2human_dir, pattern='*.csv')
dat.ceiling = do.call(rbind, lapply(filenames, function(x) read_data(model2human_dir, x)))
```

```{r}
dat$Layer = as.numeric(as.character(dat$Layer))

add_info <- function(dataframe, model_name) {
  if (grepl("GPT-2",model_name) == FALSE){
    toadd = 5
  }else{
    toadd = 10
  }
  dataframe = dataframe %>%
    mutate(Layer = max(subset(dat, Model==model_name)$Layer) + toadd) %>%
    mutate(Model = model_name)
}

models = unique(dat$Model)
  
dat.ceiling.full = do.call(rbind, lapply(models, function(x) add_info(dat.ceiling, x)))
```

```{r}
merged <- rbind(dat, dat.ceiling.full)
```


# PLOT

## breaks function x axis
```{r}
breaks_fun <- function(x) {
  if (max(x) > 40) {
    breaks = c(seq(0, 50, 10), max(x) + 10)
    breaks <- append(breaks, max(breaks) + 5)
  } else {
    breaks = c(seq(0, 25, 5), max(x) + 5)
    breaks <- append(breaks, max(breaks) + 10)
  }
}

labels_fun <- function(x) {
  labels = head(x, -1)
  labels <- append(labels, "H")
}

```


```{r}
theme_set(theme_classic(base_size = 14)) 
```

## All datasets
```{r, fig.width=15, fig.height=8}
plot_data = merged %>% filter(TrialType=="all", VoiceType=="all", grepl("HumanCeiling",Plot)==FALSE)
plot_data$Layer = as.numeric(as.character(plot_data$Layer))

ceil_data = merged %>% filter(TrialType=="all", VoiceType=="all",grepl("HumanCeiling",Plot)==TRUE)
ceil_summary <- ceil_data %>%
  group_by(Dataset) %>%
  summarise(
    MeanAccuracy = mean(Accuracy),
    sd = sd(Accuracy),
    n = n(),
    SE = sd / sqrt(n)
  )

datasets = c(ceil_summary$Dataset)

ceil_data = ceil_data %>% 
  mutate(MeanAccuracy = NA) %>%
  mutate(SE = NA)

for( dt in datasets){
  ceil_data = ceil_data %>%
    mutate(MeanAccuracy = ifelse(ceil_data$Dataset==dt, subset(ceil_summary, Dataset == dt)$MeanAccuracy, ceil_data$MeanAccuracy)) %>%
    mutate(SE = ifelse(ceil_data$Dataset==dt, subset(ceil_summary, Dataset == dt)$SE, ceil_data$SE))
}

plot.alldat <- ggplot(data = plot_data,
       mapping = aes(x=Layer, y=Accuracy, color=Dataset, group = Dataset))+
  facet_grid(~Model, scales="free_x")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0.1)+
  geom_point(data = ceil_data, aes(x=Layer, y=MeanAccuracy, color=Dataset), size=2)+
  geom_errorbar(data = ceil_data, aes(x=Layer, ymin=MeanAccuracy-SE, ymax=MeanAccuracy+SE, color=Dataset),width = 0.1) +
  geom_text(data = ceil_data, group=ceil_data$Dataset, x =ifelse(ceil_data$Model=="GPT-2", ceil_data$Layer - 6, ceil_data$Layer - 3),  y = 0.98,
            size = 2.5,
            label = "ceiling", 
            colour = "#6d6d6d") +
  #theme_classic()+
  scale_x_continuous(breaks=breaks_fun, labels=labels_fun, limits=c(NA,NA))+
  scale_y_continuous(breaks=seq(0.4,1.2,0.1))
plot.alldat

savename <- "model2plausibility_all_datasets_ceiled.png"
ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm', dpi=700)
ggsave(paste(savedir,"model2plausibility_all_datasets_ceiled.svg",sep="/"), plot=plot.alldat, height=20, width=8, units='cm')
```


## EventsAdapt

### Active Passive
```{r}
dataset = "EventsAdapt"

plot_data.voice = merged %>% filter(Dataset==dataset, TrialType=="all", grepl("HumanCeiling",Plot)==FALSE)
ceil_data.voice = merged %>% filter(Dataset==dataset, TrialType=="all",grepl("HumanCeiling",Plot)==TRUE)

ceil_summary.voice <- ceil_data.voice %>%
  group_by(VoiceType) %>%
  summarise(
    MeanAccuracy = mean(Accuracy),
    sd = sd(Accuracy),
    n = n(),
    se = sd / sqrt(n)
  )

voice_types = c(ceil_summary.voice$VoiceType)

ceil_data.voice = ceil_data.voice %>%
  mutate(MeanAccuracy = NA) %>%
  mutate(SE = NA)

for(vt in voice_types){
  ceil_data.voice = ceil_data.voice %>%
    mutate(MeanAccuracy = ifelse(ceil_data.voice$VoiceType==vt, subset(ceil_summary.voice, VoiceType == vt)$MeanAccuracy, ceil_data.voice$MeanAccuracy)) %>%
    mutate(SE = ifelse(ceil_data.voice$VoiceType==vt, subset(ceil_summary.voice, VoiceType == vt)$se, ceil_data.voice$SE))
}

plot.gen.voice <- ggplot(data = plot_data.voice,
       mapping = aes(x=Layer, y=Accuracy, color=VoiceType, group=VoiceType))+
  facet_grid(~Model, scales="free_x")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0.1)+
  geom_point(inherit.aes=FALSE, data = ceil_data.voice, aes(x=Layer, y=MeanAccuracy, color=VoiceType), size=2)+
  geom_errorbar(inherit.aes=FALSE, data = ceil_data.voice, aes(x=Layer, ymin=MeanAccuracy-SE, ymax=MeanAccuracy+SE, color=VoiceType),width = 0.1) +
    # geom_text(data = ceil_data.voice, group=ceil_data.voice$VoiceType, x =ifelse(ceil_data.voice$Model=="GPT2-xl", ceil_data.voice$Layer - 6, ceil_data.voice$Layer - 3),  y = 0.98,
    #         size = 2.5,
    #        label = "ceiling", 
    #        colour = "#6d6d6d") +
  #theme_classic()+
  scale_x_continuous(breaks=breaks_fun)+
  scale_y_continuous(breaks=seq(0.2,1,0.1))+
  scale_color_manual(values = c("all" = brewer.pal(12, "Paired")[[10]],
                                "TrainOn:active-TestOn:active" = brewer.pal(12, "Paired")[[8]],
                                "TrainOn:passive-TestOn:passive" = brewer.pal(12, "Paired")[[7]],
                                "TrainOn:active-TestOn:passive" = brewer.pal(12, "Paired")[[6]],
                                "TrainOn:passive-TestOn:active" = brewer.pal(12, "Paired")[[5]]
                                ))

savename <- "model2plausibility_EventsAdapt_active-passive_ceiled.png"
ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm', dpi=700)
```

### TrialTypes
```{r, fig.width=15, fig.height=8}
dataset = "EventsAdapt"
plot_data.tt = merged %>% filter(Dataset==dataset, VoiceType=="TrainOn:active-TestOn:active", !grepl('AAR', TrialType),grepl("HumanCeiling", Plot)==FALSE)
ceil_data.tt = merged %>% filter(Dataset==dataset, VoiceType=="TrainOn:active-TestOn:active",!grepl('AAR', TrialType),grepl("HumanCeiling", Plot)==TRUE)

ceil_summary.tt <- ceil_data.tt %>%
  group_by(TrialType) %>%
  summarise(
    MeanAccuracy = mean(Accuracy),
    sd = sd(Accuracy),
    n = n(),
    se = sd / sqrt(n)
  )

trial_types = c(ceil_summary.tt$TrialType)

ceil_data.tt = ceil_data.tt %>%
  mutate(MeanAccuracy = NA) %>%
  mutate(SE = NA)

for(tt in trial_types){
  ceil_data.tt = ceil_data.tt %>%
    mutate(MeanAccuracy = ifelse(ceil_data.tt$TrialType==tt, subset(ceil_summary.tt, TrialType == tt)$MeanAccuracy, ceil_data.tt$MeanAccuracy)) %>%
    mutate(SE = ifelse(ceil_data.tt$TrialType==tt, subset(ceil_summary.tt, TrialType == tt)$se, ceil_data.tt$SE))
}
ceil_data.tt = ceil_data.tt %>% select(-Iteration, -Accuracy) %>% distinct() %>%
  mutate(Accuracy=MeanAccuracy)

# avoid overlap
ceil_data.tt = ceil_data.tt %>% 
  mutate(Layer = ifelse(TrialType=="TrainOn:AI-TestOn:AI", Layer-0.5, 
                        ifelse(TrialType=="TrainOn:AAN-TestOn:AI", Layer+0.5, Layer)))

plot.gen.trialtype <- ggplot(data = plot_data.tt,
       mapping = aes(x=Layer, y=Accuracy, color=TrialType, group=TrialType))+
  facet_grid(~Model, scales="free_x")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0.1)+
  geom_point(data = ceil_data.tt,
              mapping=aes(x=Layer, y=MeanAccuracy, color=TrialType), size=2)+
  geom_errorbar(data = ceil_data.tt, mapping=aes(x=Layer, ymin=MeanAccuracy-SE, ymax=MeanAccuracy+SE, color=TrialType), width = 0.1)+
  scale_x_continuous(breaks=breaks_fun)+
  scale_y_continuous(breaks=seq(0.5,1,0.1))+
  scale_color_manual(values = c("all" = brewer.pal(12, "Paired")[[10]],
                                "TrainOn:AI-TestOn:AI" = brewer.pal(12, "Paired")[[2]],
                                "TrainOn:AAN-TestOn:AAN" = brewer.pal(12, "Paired")[[1]],
                                "TrainOn:AI-TestOn:AAN" = brewer.pal(12, "Paired")[[4]],
                                "TrainOn:AAN-TestOn:AI" = brewer.pal(12, "Paired")[[3]]
                                )) 
plot.gen.trialtype

savename <- "model2plausibility_EventsAdapt_AI-AAN_ceiled.png"
#ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm', dpi=700)
```

```{r}
main_plot <- plot.gen.trialtype / plot.gen.voice +
  plot_annotation(tag_levels = list(c('A', 'B'))) & 
   theme(plot.tag.position = c(0, 0.98), plot.tag = element_text(face='bold', size=18))
main_plot

savename <- "generalization_combined_plot.png"
ggsave(paste(savedir,savename,sep="/"), height=20, width=30, units='cm')
ggsave(paste(savedir,"generalization_combined_plot.svg",sep="/"), plot=main_plot, height=20, width=30, units='cm')
```
# STATS

## Divide layers by group
```{r}
merged.model = merged %>% filter(grepl("HumanCeiling",Plot)==FALSE)
merged.human = merged %>% filter(grepl("HumanCeiling",Plot)==TRUE)

merged.model.3groups = merged.model %>%
  group_by(Model) %>% 
  mutate(MaxLayer = max(Layer)) %>%
  mutate(LayerGroup = ifelse(Layer<=floor(MaxLayer/3), "early",
                             ifelse(Layer<=floor(MaxLayer/3)*2, "mid", "late"))) %>%
  mutate(LayerWithinGroup = ifelse(LayerGroup=="mid", Layer-floor(MaxLayer/3),
                                   ifelse(LayerGroup=="late", Layer-2*floor(MaxLayer/3),
                                          Layer))) %>%
  ungroup()

merged.model.3groups = merged.model.3groups %>%
  group_by(Model, LayerGroup, VoiceType, TrialType) %>% 
  mutate(cLayerWithinGroup = scale(LayerWithinGroup, scale=FALSE)) %>% 
  ungroup()

merged.human = merged.human %>% mutate(MaxLayer=NA, LayerGroup="human", LayerWithinGroup=1, cLayerWithinGroup=0)
merged.3groups = rbind(merged.model.3groups, merged.human)
```

## Contrasts
```{r}
merged.3groups$Iteration = as.factor(merged.3groups$Iteration)
merged.3groups$LayerGroup = factor(merged.3groups$LayerGroup, levels = c("human", "early", "mid", "late"))
```

## Stats

```{r}
results = merged.3groups %>%
  group_by(Dataset, Model, VoiceType, TrialType) %>%
  group_modify(~ broom::tidy(lm(Accuracy ~ LayerGroup + cLayerWithinGroup:LayerGroup, data=.x))) %>%
  filter(term!="LayerGrouphuman:cLayerWithinGroup")
```

## Group by comparison category and MC correct

```{r}
mc_correct <- function(results) {
  results = results %>%
    group_by(term) %>%
    mutate(pValAdjusted = p.adjust(p.value, method="fdr", n=length(p.value))) %>%
    mutate(pLabel= plabel(pValAdjusted)) %>%
    mutate(pValFinal = ifelse(pValAdjusted<0.001, "<0.001", as.character(round(pValAdjusted,3)))) %>%
    ungroup()
  return(results)
}

prettify_results <- function(results.clean) {

reported_params = c("Ceiling (human ratings)",
                    "Early layers > human",
                    "Middle layers > human",
                    "Late layers > human",
                    "Early layers, trend",
                    "Middle layers, trend",
                    "Late layers, trend")

results.clean = results.clean %>%
  rename(Parameter=term) %>% 
  mutate(Parameter = recode(Parameter, 
                            "(Intercept)"="Ceiling (human ratings)",
                            "LayerGroupearly"="Early layers > human",
                            "LayerGroupearly:cLayerWithinGroup"="Early layers, trend",
                            "LayerGroupmid"="Middle layers > human",
                            "LayerGroupmid:cLayerWithinGroup"="Middle layers, trend",
                            "LayerGrouplate"="Late layers > human",
                            "LayerGrouplate:cLayerWithinGroup"="Late layers, trend")) %>%
  mutate(Parameter = factor(Parameter, levels=reported_params)) 
return(results.clean)
}
```

### 3 datasets

```{r}
results.3datasets = results %>% filter(VoiceType=="all", TrialType=="all") %>%
  mc_correct()
savename <- "probing_stats_3datasets_full.csv"
write.csv(results.3datasets, paste(savedir,savename,sep="/"), row.names=FALSE)
```

```{r}
# restructure 
results.clean = results.3datasets %>% 
  mutate(Value = ifelse(pValAdjusted<0.05, 
                        paste(round(estimate, 2), pLabel, sep=" "),
                        "")) %>%
  select(Dataset, Model, term, Value) %>% 
  spread(Model, Value) %>%
  prettify_results() %>%
  arrange(Dataset, Parameter)

savename <- "probing_stats_3datasets_clean.csv"
write.csv(results.clean, paste(savedir,savename,sep="/"), row.names=FALSE)
```

### Active Passive

```{r}
results.voice = results %>% filter(Dataset=="EventsAdapt", TrialType=="all") %>%
  mc_correct() %>%
  select(-Dataset, -TrialType)
savename <- "probing_stats_voice_full.csv"
write.csv(results.voice, paste(savedir,savename,sep="/"), row.names=FALSE)
```

```{r}
# restructure 
results.clean = results.voice %>% 
  mutate(Value = ifelse(pValAdjusted<0.05, 
                        paste(round(estimate, 2), pLabel, sep=" "),
                        "")) %>%
  select(VoiceType, Model, term, Value) %>% 
  spread(Model, Value) %>%
  prettify_results() %>%
  arrange(VoiceType, Parameter)

savename <- "probing_stats_voice_clean.csv"
write.csv(results.clean, paste(savedir,savename,sep="/"), row.names=FALSE)
```

### TrialType

```{r}
results.trialtype = results %>% filter(Dataset=="EventsAdapt", 
                                       VoiceType=="TrainOn:active-TestOn:active") %>%
  mc_correct() %>%
  select(-Dataset, -VoiceType)
savename <- "probing_stats_trialtype_full.csv"
write.csv(results.trialtype, paste(savedir,savename,sep="/"), row.names=FALSE)
```

```{r}
# restructure 
results.clean = results.trialtype %>% 
  mutate(Value = ifelse(pValAdjusted<0.05, 
                        paste(round(estimate, 2), pLabel, sep=" "),
                        "")) %>%
  select(TrialType, Model, term, Value) %>% 
  spread(Model, Value) %>%
  prettify_results() %>%
  arrange(TrialType, Parameter)

savename <- "probing_stats_trialtype_clean.csv"
write.csv(results.clean, paste(savedir,savename,sep="/"), row.names=FALSE)
```
