---
title: "Probing results"
output: html_notebook
---

# SETUP

```{r setup, include=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) 
library(ggplot2)
library(dplyr)
library(tidyr)
library(stringr)
library(grid)
library(gridExtra)
library(operator.tools)
library(lme4)
library(lmerTest)
library(cocor)
library(patchwork)
library(gtools)

source('dataloader_utils.R') #includes normalizations, read_data functions
source('stats_utils.R')

# Suppress summarise info
options(dplyr.summarise.inform = FALSE)
```

## Output dir
```{r}
path <- paste("results/")
ifelse(!dir.exists(path), dir.create(path), FALSE)
savedir <- paste(path,"Probing",sep='')
ifelse(!dir.exists(savedir), dir.create(savedir), FALSE)
```


# READ DATA
```{r}
probing_dir = "../probing/parallel_layers"
datafile = "all_combined_kfold.csv"

dat = read.csv(paste(probing_dir, datafile, sep="/"))

dat$Layer = as.factor(dat$Layer)
```

# STATS

```{r}
dat.DTFit = dat %>% filter(Dataset=="DTFit")

m.DTFit = lm(Accuracy~Layer:Model, data=dat.DTFit)
summary(m.DTFit)
```

# PLOT

## All datasets
```{r}
ggplot(data = dat %>% filter(TrialType=="normal", VoiceType=="normal"),
       mapping = aes(x=Layer, y=Accuracy, color=Dataset))+
  facet_wrap(~Model, scales="free")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun.y='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0.1)+
  theme_classic()

savename <- "Probing_all_datasets.png"
ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm')
```

## DTFit
```{r}
dataset = "DTFit"

ggplot(data = dat %>% filter(Dataset==dataset),
       mapping = aes(x=Layer, y=Accuracy))+
  facet_wrap(~Plot, scales="free")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun.y='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               color = 'black', size = 0.5, width=0.1)+
  theme_classic()

savename <- "Probing_DTFit.png"
ggsave(paste(savedir,savename,sep="/"), width=16, height=8, units='cm')
```

## EventsRev
```{r}
dataset = "EventsRev"

ggplot(data = dat %>% filter(Dataset==dataset),
       mapping = aes(x=Layer, y=Accuracy))+
  facet_wrap(~Plot, scales="free")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun.y='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               color = 'black', size = 0.5, width=0.1)+
  theme_classic()

savename <- "Probing_EventsRev.png"
ggsave(paste(savedir,savename,sep="/"), width=16, height=8, units='cm')
```

## EventsAdapt

### Active Passive
```{r}
dataset = "EventsAdapt"

ggplot(data = dat %>% filter(Dataset==dataset, TrialType=="normal"),
       mapping = aes(x=Layer, y=Accuracy, color=VoiceType))+
  facet_wrap(~Model, scales="free")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun.y='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0)+
  theme_classic()

savename <- "Probing_EventsAdapt_active-passive.png"
ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm')
```


### Active Passive
```{r}
dataset = "EventsAdapt"

ggplot(data = dat %>% filter(Dataset==dataset, VoiceType=="active-active"),
       mapping = aes(x=Layer, y=Accuracy, color=TrialType))+
  facet_wrap(~Model, scales="free")+
  geom_hline(yintercept=.5, linetype='dotted')+
  geom_hline(yintercept=1, linetype='dotted')+
  stat_summary(geom='line', fun.y='mean')+
  stat_summary(geom='errorbar', fun.data='mean_se',
               size = 0.2, width=0)+
  theme_classic()

savename <- "Probing_EventsAdapt_AI-AAN.png"
ggsave(paste(savedir,savename,sep="/"), width=20, height=8, units='cm')
```